# Generated by Django 5.2.2 on 2025-09-21 14:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('b2b', '0002_orderitem_attributes_product_attributes_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Brand',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True)),
                ('slug', models.SlugField(blank=True, max_length=255)),
                ('woo_id', models.BigIntegerField(blank=True, null=True, unique=True)),
                ('logo_url', models.URLField(blank=True)),
            ],
        ),
        migrations.RenameField(
            model_name='orderitem',
            old_name='attributes',
            new_name='variant_attrs',
        ),
        migrations.AddField(
            model_name='product',
            name='brand',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='products', to='b2b.brand'),
        ),
        migrations.CreateModel(
            name='Facet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('ingredient', 'Ingredient'), ('effect', 'EffectiveFor'), ('season', 'Season')], max_length=32)),
                ('name', models.CharField(max_length=255)),
                ('slug', models.SlugField(blank=True, max_length=255)),
                ('woo_term_id', models.BigIntegerField(blank=True, null=True)),
            ],
            options={
                'unique_together': {('type', 'name')},
            },
        ),
        migrations.AddField(
            model_name='product',
            name='facets',
            field=models.ManyToManyField(blank=True, related_name='products', to='b2b.facet'),
        ),
        migrations.CreateModel(
            name='ProductVariant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('woo_variation_id', models.BigIntegerField(unique=True)),
                ('sku', models.CharField(blank=True, max_length=128)),
                ('attributes', models.JSONField(blank=True, default=dict)),
                ('retail_price', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('wholesale_price', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('stock_qty', models.IntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
                ('image_url', models.URLField(blank=True)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='variants', to='b2b.product')),
            ],
        ),
        migrations.AlterUniqueTogether(
            name='orderitem',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='orderitem',
            name='variant',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='b2b.productvariant'),
        ),
        migrations.AlterUniqueTogether(
            name='orderitem',
            unique_together={('order', 'product', 'variant')},
        ),
    ]
