# Generated by Django 5.2.2 on 2025-09-28 19:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('b2b', '0003_brand_rename_attributes_orderitem_variant_attrs_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='productvariant',
            name='weight_g',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
