# Generated by Django 5.2.2 on 2025-09-29 21:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('b2b', '0004_productvariant_weight_g'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('draft', 'Чернетка'), ('submitted', 'Надіслано'), ('confirmed', 'Підтверджено'), ('fulfilled', 'Відвантажено'), ('cancelled', 'Скасовано')], default='draft', max_length=16),
        ),
    ]
