# Generated by Django 5.0.6 on 2025-09-30 21:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('b2b', '0005_alter_order_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='shipped_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='order',
            name='shipping_provider',
            field=models.CharField(blank=True, default='Nova Poshta', max_length=64),
        ),
        migrations.AddField(
            model_name='order',
            name='shipping_ttn',
            field=models.CharField(blank=True, max_length=64),
        ),
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('draft', 'Чернетка'), ('submitted', 'Очікує підтвердження'), ('pending_payment', 'Очікує оплату'), ('shipped', 'Відправлено'), ('cancelled', 'Скасовано')], default='draft', max_length=20),
        ),
    ]
