# Generated by Django 5.0.6 on 2025-10-05 20:58

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('b2b', '0006_order_shipped_at_order_shipping_provider_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='shipping_provider',
        ),
        migrations.AddField(
            model_name='dealer',
            name='telegram_chat_id',
            field=models.CharField(blank=True, max_length=32, null=True),
        ),
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('draft', 'Чернетка'), ('submitted', 'Надіслано'), ('pending_payment', 'Очікує оплату'), ('shipped', 'Відправлено'), ('cancelled', 'Скасовано')], default='draft', max_length=20),
        ),
        migrations.CreateModel(
            name='Address',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text='Short label, e.g. Shop #1', max_length=100)),
                ('city_name', models.CharField(max_length=120)),
                ('city_ref', models.CharField(max_length=64)),
                ('warehouse_name', models.CharField(max_length=200)),
                ('warehouse_ref', models.CharField(max_length=64)),
                ('recipient_name', models.CharField(max_length=120)),
                ('recipient_phone', models.CharField(max_length=30)),
                ('is_default', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('dealer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='addresses', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='order',
            name='shipping_address',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='orders', to='b2b.address'),
        ),
    ]
