# Generated by Django 5.0.6 on 2025-10-06 21:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('b2b', '0008_order_shipping_city_order_shipping_city_ref_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='shipping_np_ref',
            field=models.CharField(blank=True, max_length=64),
        ),
    ]
