# Generated by Django 5.0.6 on 2025-10-10 19:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('b2b', '0009_order_shipping_np_ref'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='cost_price',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
    ]
