# Generated by Django 5.0.6 on 2025-11-08 07:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('b2b', '0010_product_cost_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderitem',
            name='cost_total',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True),
        ),
        migrations.AddField(
            model_name='orderitem',
            name='cost_unit',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
    ]
