# Generated by Django 5.0.6 on 2025-12-18 22:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('b2b', '0011_orderitem_cost_total_orderitem_cost_unit'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderitem',
            name='cogs_total',
            field=models.DecimalField(blank=True, decimal_places=2, default=None, max_digits=14, null=True),
        ),
    ]
