# Generated by Django 5.0.6 on 2025-12-21 21:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('b2b', '0012_orderitem_cogs_total'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='orderitem',
            name='cogs_total',
        ),
    ]
