# Generated by ChatGPT on 2026-02-27

from django.db import migrations, models
from django.db.models import Q


class Migration(migrations.Migration):

    dependencies = [
        ("b2b", "0013_remove_orderitem_cogs_total"),
    ]

    operations = [
        migrations.AddField(
            model_name="order",
            name="channel",
            field=models.CharField(db_index=True, default="b2b", max_length=20),
        ),
        migrations.AddField(
            model_name="order",
            name="external_id",
            field=models.CharField(blank=True, db_index=True, default="", max_length=64),
        ),
        migrations.AddField(
            model_name="order",
            name="external_status",
            field=models.CharField(blank=True, default="", max_length=64),
        ),
        migrations.AddField(
            model_name="order",
            name="external_created_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="order",
            name="external_payload",
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddConstraint(
            model_name="order",
            constraint=models.UniqueConstraint(
                condition=~Q(external_id=""),
                fields=("channel", "external_id"),
                name="uniq_order_external_channel_id",
            ),
        ),
    ]
