# Generated by Django 5.0.6 on 2025-11-08 07:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('b2b', '0011_orderitem_cost_total_orderitem_cost_unit'),
    ]

    operations = [
        migrations.CreateModel(
            name='InventoryLot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('qty_in', models.PositiveIntegerField()),
                ('qty_reserved', models.PositiveIntegerField(default=0)),
                ('qty_out', models.PositiveIntegerField(default=0)),
                ('unit_cost', models.DecimalField(decimal_places=2, max_digits=10)),
                ('reference', models.CharField(blank=True, max_length=120)),
                ('received_at', models.DateTimeField(auto_now_add=True)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lots', to='b2b.product')),
            ],
            options={
                'ordering': ['received_at', 'id'],
            },
        ),
        migrations.CreateModel(
            name='InventoryReservation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('qty', models.PositiveIntegerField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('lot', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reservations', to='warehouse.inventorylot')),
                ('order_item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lot_reservations', to='b2b.orderitem')),
            ],
        ),
        migrations.CreateModel(
            name='InventoryMove',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('move_type', models.CharField(choices=[('IN', 'Inbound'), ('RSV', 'Reserve'), ('REL', 'Release'), ('SHP', 'Ship'), ('ADJ', 'Adjust')], max_length=3)),
                ('qty', models.IntegerField()),
                ('note', models.CharField(blank=True, max_length=200)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('lot', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='warehouse.inventorylot')),
                ('order', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='b2b.order')),
                ('order_item', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='b2b.orderitem')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='b2b.product')),
            ],
            options={
                'indexes': [models.Index(fields=['product'], name='warehouse_i_product_36a03a_idx'), models.Index(fields=['move_type', 'created_at'], name='warehouse_i_move_ty_c20af1_idx')],
            },
        ),
    ]
