# Generated by Django 5.0.6 on 2025-12-18 22:55

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('b2b', '0012_orderitem_cogs_total'),
        ('warehouse', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='LotReservation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('qty', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
            ],
        ),
        migrations.RemoveField(
            model_name='inventoryreservation',
            name='lot',
        ),
        migrations.RemoveField(
            model_name='inventoryreservation',
            name='order_item',
        ),
        migrations.AlterModelOptions(
            name='inventorymove',
            options={'ordering': ['-created_at', '-id']},
        ),
        migrations.RemoveIndex(
            model_name='inventorymove',
            name='warehouse_i_product_36a03a_idx',
        ),
        migrations.RemoveField(
            model_name='inventorylot',
            name='qty_in',
        ),
        migrations.RemoveField(
            model_name='inventorylot',
            name='qty_out',
        ),
        migrations.RemoveField(
            model_name='inventorylot',
            name='qty_reserved',
        ),
        migrations.RemoveField(
            model_name='inventorylot',
            name='reference',
        ),
        migrations.RemoveField(
            model_name='inventorymove',
            name='qty',
        ),
        migrations.AddField(
            model_name='inventorylot',
            name='currency',
            field=models.CharField(blank=True, default='UAH', max_length=8),
        ),
        migrations.AddField(
            model_name='inventorylot',
            name='external_ref',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
        migrations.AddField(
            model_name='inventorylot',
            name='note',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='inventorylot',
            name='qty_available',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='inventorylot',
            name='qty_received',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='inventorylot',
            name='supplier',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
        migrations.AddField(
            model_name='inventorymove',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='inventory_moves', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='inventorymove',
            name='qty_delta',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='inventorymove',
            name='unit_cost_snapshot',
            field=models.DecimalField(blank=True, decimal_places=4, max_digits=12, null=True),
        ),
        migrations.AlterField(
            model_name='inventorylot',
            name='received_at',
            field=models.DateTimeField(db_index=True, default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='inventorylot',
            name='unit_cost',
            field=models.DecimalField(decimal_places=4, default=0, max_digits=12),
        ),
        migrations.AlterField(
            model_name='inventorymove',
            name='created_at',
            field=models.DateTimeField(db_index=True, default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='inventorymove',
            name='lot',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='moves', to='warehouse.inventorylot'),
        ),
        migrations.AlterField(
            model_name='inventorymove',
            name='move_type',
            field=models.CharField(choices=[('receipt', 'Receipt'), ('adjustment', 'Adjustment'), ('write_off', 'Write-off'), ('reserve', 'Reserve'), ('unreserve', 'Unreserve'), ('ship', 'Ship')], db_index=True, max_length=16),
        ),
        migrations.AlterField(
            model_name='inventorymove',
            name='note',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AlterField(
            model_name='inventorymove',
            name='order',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='inventory_moves', to='b2b.order'),
        ),
        migrations.AlterField(
            model_name='inventorymove',
            name='order_item',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='inventory_moves', to='b2b.orderitem'),
        ),
        migrations.AlterField(
            model_name='inventorymove',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='inventory_moves', to='b2b.product'),
        ),
        migrations.AddIndex(
            model_name='inventorymove',
            index=models.Index(fields=['product', 'created_at'], name='warehouse_i_product_7f4789_idx'),
        ),
        migrations.AddIndex(
            model_name='inventorymove',
            index=models.Index(fields=['order'], name='warehouse_i_order_i_60c594_idx'),
        ),
        migrations.AddField(
            model_name='lotreservation',
            name='lot',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='reservations', to='warehouse.inventorylot'),
        ),
        migrations.AddField(
            model_name='lotreservation',
            name='order',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lot_reservations', to='b2b.order'),
        ),
        migrations.AddField(
            model_name='lotreservation',
            name='order_item',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lot_reservations', to='b2b.orderitem'),
        ),
        migrations.DeleteModel(
            name='InventoryReservation',
        ),
        migrations.AddIndex(
            model_name='lotreservation',
            index=models.Index(fields=['order'], name='warehouse_l_order_i_8fb63e_idx'),
        ),
        migrations.AddIndex(
            model_name='lotreservation',
            index=models.Index(fields=['order_item'], name='warehouse_l_order_i_45180d_idx'),
        ),
        migrations.AddIndex(
            model_name='lotreservation',
            index=models.Index(fields=['lot'], name='warehouse_l_lot_id_e45d09_idx'),
        ),
    ]
