# Generated by Django 5.0.6 on 2025-12-21 21:11

import django.db.models.deletion
import django.utils.timezone
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('b2b', '0013_remove_orderitem_cogs_total'),
        ('warehouse', '0002_lotreservation_remove_inventoryreservation_lot_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='inventorymove',
            name='warehouse_i_move_ty_c20af1_idx',
        ),
        migrations.RemoveIndex(
            model_name='lotreservation',
            name='warehouse_l_order_i_8fb63e_idx',
        ),
        migrations.AddField(
            model_name='inventorylot',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='inventorylot',
            name='currency',
            field=models.CharField(choices=[('UAH', 'UAH'), ('USD', 'USD')], default='UAH', max_length=3),
        ),
        migrations.AlterField(
            model_name='inventorylot',
            name='external_ref',
            field=models.CharField(blank=True, default='', max_length=120),
        ),
        migrations.AlterField(
            model_name='inventorylot',
            name='note',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
        migrations.AlterField(
            model_name='inventorylot',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='inventory_lots', to='b2b.product'),
        ),
        migrations.AlterField(
            model_name='inventorylot',
            name='qty_available',
            field=models.PositiveIntegerField(),
        ),
        migrations.AlterField(
            model_name='inventorylot',
            name='qty_received',
            field=models.PositiveIntegerField(),
        ),
        migrations.AlterField(
            model_name='inventorylot',
            name='received_at',
            field=models.DateField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='inventorylot',
            name='supplier',
            field=models.CharField(blank=True, default='', max_length=120),
        ),
        migrations.AlterField(
            model_name='inventorylot',
            name='unit_cost',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12),
        ),
        migrations.AlterField(
            model_name='inventorymove',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='inventorymove',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='inventorymove',
            name='lot',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='moves', to='warehouse.inventorylot'),
        ),
        migrations.AlterField(
            model_name='inventorymove',
            name='move_type',
            field=models.CharField(choices=[('receipt', 'Receipt'), ('adjust', 'Adjust'), ('reserve', 'Reserve'), ('release', 'Release'), ('ship', 'Ship')], max_length=16),
        ),
        migrations.AlterField(
            model_name='inventorymove',
            name='note',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
        migrations.AlterField(
            model_name='inventorymove',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='inventory_moves', to='b2b.product'),
        ),
        migrations.AlterField(
            model_name='inventorymove',
            name='qty_delta',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='inventorymove',
            name='unit_cost_snapshot',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True),
        ),
        migrations.AlterField(
            model_name='lotreservation',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='lotreservation',
            name='lot',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reservations', to='warehouse.inventorylot'),
        ),
        migrations.AlterField(
            model_name='lotreservation',
            name='qty',
            field=models.PositiveIntegerField(),
        ),
        migrations.AddIndex(
            model_name='inventorylot',
            index=models.Index(fields=['product', 'received_at', 'id'], name='warehouse_i_product_a30a23_idx'),
        ),
        migrations.AddIndex(
            model_name='lotreservation',
            index=models.Index(fields=['order', 'created_at'], name='warehouse_l_order_i_3a8e2d_idx'),
        ),
    ]
