# Generated by Django 5.0.6 on 2025-12-26 18:18

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('b2b', '0013_remove_orderitem_cogs_total'),
        ('warehouse', '0003_remove_inventorymove_warehouse_i_move_ty_c20af1_idx_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='InventoryReservation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('qty', models.PositiveIntegerField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),

        migrations.AlterModelOptions(
            name='inventorymove',
            options={},
        ),
        migrations.RemoveIndex(
            model_name='inventorylot',
            name='warehouse_i_product_a30a23_idx',
        ),
        migrations.RemoveIndex(
            model_name='inventorymove',
            name='warehouse_i_product_7f4789_idx',
        ),
        migrations.RemoveIndex(
            model_name='inventorymove',
            name='warehouse_i_order_i_60c594_idx',
        ),
        migrations.RemoveField(
            model_name='inventorylot',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='inventorylot',
            name='currency',
        ),
        migrations.RemoveField(
            model_name='inventorylot',
            name='external_ref',
        ),
        migrations.RemoveField(
            model_name='inventorylot',
            name='note',
        ),
        migrations.RemoveField(
            model_name='inventorylot',
            name='qty_available',
        ),
        migrations.RemoveField(
            model_name='inventorylot',
            name='qty_received',
        ),
        migrations.RemoveField(
            model_name='inventorylot',
            name='supplier',
        ),
        migrations.RemoveField(
            model_name='inventorymove',
            name='created_by',
        ),
        migrations.RemoveField(
            model_name='inventorymove',
            name='qty_delta',
        ),
        migrations.RemoveField(
            model_name='inventorymove',
            name='unit_cost_snapshot',
        ),
        migrations.AddField(
            model_name='inventorylot',
            name='qty_in',
            field=models.PositiveIntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='inventorylot',
            name='qty_out',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='inventorylot',
            name='qty_reserved',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='inventorylot',
            name='reference',
            field=models.CharField(blank=True, max_length=120),
        ),
        migrations.AddField(
            model_name='inventorymove',
            name='qty',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='inventorylot',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lots', to='b2b.product'),
        ),
        migrations.AlterField(
            model_name='inventorylot',
            name='received_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='inventorylot',
            name='unit_cost',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
        migrations.AlterField(
            model_name='inventorymove',
            name='lot',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='warehouse.inventorylot'),
        ),
        migrations.AlterField(
            model_name='inventorymove',
            name='move_type',
            field=models.CharField(choices=[('IN', 'Inbound'), ('RSV', 'Reserve'), ('REL', 'Release'), ('SHP', 'Ship'), ('ADJ', 'Adjust')], max_length=3),
        ),
        migrations.AlterField(
            model_name='inventorymove',
            name='note',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AlterField(
            model_name='inventorymove',
            name='order',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='b2b.order'),
        ),
        migrations.AlterField(
            model_name='inventorymove',
            name='order_item',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='b2b.orderitem'),
        ),
        migrations.AlterField(
            model_name='inventorymove',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='b2b.product'),
        ),
        migrations.AddIndex(
            model_name='inventorymove',
            index=models.Index(fields=['product'], name='warehouse_i_product_36a03a_idx'),
        ),
        migrations.AddIndex(
            model_name='inventorymove',
            index=models.Index(fields=['move_type', 'created_at'], name='warehouse_i_move_ty_c20af1_idx'),
        ),
        migrations.AddField(
            model_name='inventoryreservation',
            name='lot',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reservations', to='warehouse.inventorylot'),
        ),
        migrations.AddField(
            model_name='inventoryreservation',
            name='order_item',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lot_reservations', to='b2b.orderitem'),
        ),
        migrations.DeleteModel(
            name='LotReservation',
        ),
    ]
