# Generated by Django 5.0.6 on 2026-01-03 08:09

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('b2b', '0013_remove_orderitem_cogs_total'),
        ('warehouse', '0004_inventoryreservation_remove_lotreservation_lot_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='InboundReceipt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('currency', models.CharField(default='UAH', max_length=10)),
                ('supplier', models.CharField(blank=True, max_length=120)),
                ('external_ref', models.CharField(blank=True, max_length=120)),
                ('received_date', models.DateField(default=django.utils.timezone.now)),
                ('note', models.CharField(blank=True, max_length=200)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ('-received_date', '-id'),
            },
        ),
        migrations.CreateModel(
            name='InboundReceiptLine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('qty', models.PositiveIntegerField()),
                ('unit_cost', models.DecimalField(decimal_places=2, max_digits=10)),
            ],
            options={
                'ordering': ('id',),
            },
        ),
        migrations.AlterModelOptions(
            name='inventorylot',
            options={'ordering': ('-received_at', '-id')},
        ),
        migrations.AlterModelOptions(
            name='inventorymove',
            options={'ordering': ('-created_at', '-id')},
        ),
        migrations.AlterModelOptions(
            name='inventoryreservation',
            options={'ordering': ('-created_at', '-id')},
        ),
        migrations.AddField(
            model_name='inventorylot',
            name='currency',
            field=models.CharField(default='UAH', max_length=10),
        ),
        migrations.AddField(
            model_name='inventorylot',
            name='external_ref',
            field=models.CharField(blank=True, max_length=120),
        ),
        migrations.AddField(
            model_name='inventorylot',
            name='note',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='inventorylot',
            name='supplier',
            field=models.CharField(blank=True, max_length=120),
        ),
        migrations.AddIndex(
            model_name='inventorylot',
            index=models.Index(fields=['product', 'received_at'], name='warehouse_i_product_a30a23_idx'),
        ),
        migrations.AddField(
            model_name='inboundreceiptline',
            name='created_lot',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_from_line', to='warehouse.inventorylot'),
        ),
        migrations.AddField(
            model_name='inboundreceiptline',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='b2b.product'),
        ),
        migrations.AddField(
            model_name='inboundreceiptline',
            name='receipt',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lines', to='warehouse.inboundreceipt'),
        ),
    ]
