# Generated by Django 5.0.6 on 2025-11-07 19:59

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('audit', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='loginevent',
            name='kind',
        ),
        migrations.AddField(
            model_name='loginevent',
            name='is_staff',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='loginevent',
            name='path',
            field=models.CharField(blank=True, max_length=512),
        ),
        migrations.AddField(
            model_name='loginevent',
            name='session_key',
            field=models.CharField(blank=True, max_length=40),
        ),
        migrations.AddField(
            model_name='loginevent',
            name='status',
            field=models.CharField(choices=[('success', 'Success'), ('failed', 'Failed'), ('logout', 'Logout')], default='Success', max_length=16),
        ),
        migrations.AlterField(
            model_name='loginevent',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='loginevent',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='login_events', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddIndex(
            model_name='loginevent',
            index=models.Index(fields=['created_at'], name='audit_login_created_fc75ee_idx'),
        ),
        migrations.AddIndex(
            model_name='loginevent',
            index=models.Index(fields=['status'], name='audit_login_status_bb37f6_idx'),
        ),
        migrations.AddIndex(
            model_name='loginevent',
            index=models.Index(fields=['username'], name='audit_login_usernam_e62d10_idx'),
        ),
    ]
